// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CSRParser
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("subject")]
        public Subject Subject { get; set; }

        [JsonProperty("public_key")]
        public PublicKey PublicKey { get; set; }

        [JsonProperty("signature_algorithm")]
        public string SignatureAlgorithm { get; set; }

        [JsonProperty("extensions")]
        public object[] Extensions { get; set; }

        [JsonProperty("fingerprints")]
        public Fingerprints Fingerprints { get; set; }

        [JsonProperty("pem")]
        public string Pem { get; set; }

        [JsonProperty("size_bytes")]
        public long SizeBytes { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("is_valid")]
        public bool IsValid { get; set; }
    }

    public partial class Fingerprints
    {
        [JsonProperty("sha1")]
        public string Sha1 { get; set; }

        [JsonProperty("sha256")]
        public string Sha256 { get; set; }

        [JsonProperty("md5")]
        public string Md5 { get; set; }
    }

    public partial class PublicKey
    {
        [JsonProperty("algorithm")]
        public string Algorithm { get; set; }

        [JsonProperty("size_bits")]
        public long SizeBits { get; set; }

        [JsonProperty("exponent")]
        public long Exponent { get; set; }
    }

    public partial class Subject
    {
        [JsonProperty("common_name")]
        public object CommonName { get; set; }

        [JsonProperty("organization")]
        public object Organization { get; set; }

        [JsonProperty("organizational_unit")]
        public object OrganizationalUnit { get; set; }

        [JsonProperty("locality")]
        public object Locality { get; set; }

        [JsonProperty("state")]
        public object State { get; set; }

        [JsonProperty("country")]
        public object Country { get; set; }

        [JsonProperty("email")]
        public object Email { get; set; }
    }
}
